# Generated by Django 3.1.7 on 2021-06-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projekts',
            new_name='Project',
        ),
    ]
