# Generated by Django 3.2.8 on 2021-11-15 15:23

from django.db import migrations, models
import mysite.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=mysite.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
