# Generated by Django 3.2.10 on 2022-01-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
