# Generated by Django 3.2.10 on 2022-01-03 14:14

from django.db import migrations, models
import mysite.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=mysite.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
