# Generated by Django 3.2.10 on 2022-01-04 08:50

from django.db import migrations, models
import mysite.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, upload_to=mysite.utilities.get_timestamp_path, verbose_name='файл'),
        ),
    ]
