# Generated by Django 3.2.8 on 2021-11-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
    ]
