# Generated by Django 3.2.8 on 2021-10-25 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mysite.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20211025_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название фото')),
                ('image', models.ImageField(blank=True, upload_to=mysite.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('full_text', models.TextField(verbose_name='Проект')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
