# Generated by Django 3.2.8 on 2021-11-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image',
        ),
        migrations.AlterField(
            model_name='photos',
            name='autor',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
    ]
