# Generated by Django 3.2.8 on 2021-11-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20211104_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='project',
        ),
    ]
