# Generated by Django 3.2.8 on 2021-11-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_image'),
        ('photos', '0003_remove_photos_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
