# Generated by Django 3.2.8 on 2021-11-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photos_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='full_text',
        ),
    ]
