# Generated by Django 3.2.8 on 2021-11-07 08:26

from django.db import migrations, models
import mysite.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_remove_photos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(blank=True, upload_to=mysite.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
