# Generated by Django 3.2.10 on 2022-01-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_file'),
        ('photos', '0008_photos_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Фотогр2афия', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RemoveField(
            model_name='photos',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='title',
        ),
        migrations.AddField(
            model_name='photos',
            name='describe',
            field=models.CharField(blank=True, max_length=50, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект фото'),
        ),
    ]
