# Generated by Django 3.2.8 on 2021-11-05 05:48

from django.db import migrations, models
import mysite.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_advuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=mysite.utilities.get_timestamp_path, verbose_name='Изoбpaжeниe')),
                ('desc', models.TextField(verbose_name='Oпиcaниe')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изoбpaжeния',
            },
        ),
    ]
