# Generated by Django 3.2.8 on 2021-11-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
