# Generated by Django 3.2.10 on 2022-01-05 14:40

from django.db import migrations, models
import django.db.models.deletion
import mysite.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=mysite.utilities.get_timestamp_path, verbose_name='Файл')),
                ('describe', models.CharField(blank=True, max_length=50, verbose_name='Описание файла')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
